### ISSUE TITLE
update node version to 16

### ISSUE THREAD

**Issue by watahani** [cssjpn/blog-example#7]
actions/checkout@v2 use node 12 which is deprecated in Github Actions by default.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

I think we have tow options

- specify node-version using [setup-node](https://github.com/marketplace/actions/setup-node-js-environment) action

```yaml
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
```

- update to checkout@v3

```yaml
    steps:
      - uses: actions/checkout@v3 #node 16 by default
```
